### ISSUE TITLE
Upgrade to Slick 3.0

### ISSUE THREAD

**Issue by adrien-aubel** [slick/play-slick-codegen#2]
@cvogt it would be awesome to have this repository upgraded to Slick 3.0 if you have the time!
Thank you so much :)

**Comment by PiyushMishra** [comment]
lets do it.

**Comment by hepin1989** [comment]
there is a sbt plugin ,it's https://github.com/tototoshi/sbt-slick-codegen
it works fine for me

**Comment by cvogt** [comment]
@adrien-aubel @PiyushMishra not a lot of time right now. How about a contribution? Maybe ask on the mailing list, if someone can help out
